environment:
  matrix:
  - nodejs_version: "10"

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm run auto-test

# Upload results to appveyor
on_finish:
  - npm run coverage
  - curl -F 'file=@$APPVEYOR_BUILD_FOLDER/TEST-RESULTS.xml' "https://ci.appveyor.com/api/testresults/junit/$APPVEYOR_JOB_ID"

# Do a build of our app
build_script:
  - npm run ci-build